build: off
clone_depth: 5
platform: x64
configuration: Release

environment:
    PKG_NAME: bgen_reader
    PYTHON: "C:\\Python36-x64"

install:
    - mkdir build.%BDIR% && cd build.%BDIR%
    - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/horta/zlib.install/master/install.bat', 'install-zlib.bat')" && install-zlib.bat
    - set PATH=%programfiles%\zlib\bin;%PATH%
    - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/horta/zstd.install/master/install.bat', 'install-zstd.bat')" && call install-zstd.bat
    - set PATH=%programfiles%\zstd\bin;%PATH%
    - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/horta/almosthere/master/install.bat', 'install-athr.bat')" && call install-athr.bat
    - set PATH=%programfiles%\athr\bin;%PATH%
    - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/limix/bgen/master/install.bat', 'install-bgen.bat')" && install-bgen.bat
    - set PATH=%programfiles%\bgen\bin;%PATH%
    - set INCLUDE=%programfiles%\bgen\include;%INCLUDE%

build_script:
    - cd %APPVEYOR_BUILD_FOLDER%
    - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/horta/ci/master/appveyor.bat', 'appveyor.bat')" && appveyor.bat
