build: off
clone_depth: 5
platform: x64
configuration: Release

environment:
    PKG_NAME: bgen_reader
    PYTHON: "C:\\Python36-x64"
    ARCH: x64

install:
    - mkdir build.%BDIR% && cd build.%BDIR%
    - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/horta/zlib.install/master/install.bat', 'install-zlib.bat')" && install-zlib.bat
    - set PATH=%programfiles%\zlib\bin;%PATH%
    - set LIBRARY_INC=%programfiles%\zlib\include;%LIBRARY_INC%
    - set LIBRARY_LIB=%programfiles%\zlib\lib;%LIBRARY_LIB%
    - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/horta/zstd.install/master/install.bat', 'install-zstd.bat')" && call install-zstd.bat
    - set PATH=%programfiles%\zstd\bin;%PATH%
    - set LIBRARY_INC=%programfiles%\zstd\include;%LIBRARY_INC%
    - set LIBRARY_LIB=%programfiles%\zstd\lib;%LIBRARY_LIB%
    - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/horta/almosthere/master/install.bat', 'install-athr.bat')" && call install-athr.bat
    - set PATH=%programfiles%\athr\bin;%PATH%
    - set LIBRARY_INC=%programfiles%\athr\include;%LIBRARY_INC%
    - set LIBRARY_LIB=%programfiles%\athr\lib;%LIBRARY_LIB%
    - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/limix/bgen/master/install.bat', 'install-bgen.bat')" && install-bgen.bat
    - set PATH=%programfiles%\bgen\bin;%PATH%
    - set LIBRARY_INC=%programfiles%\bgen\include;%LIBRARY_INC%
    - set LIBRARY_LIB=%programfiles%\bgen\lib;%LIBRARY_LIB%

build_script:
    - cd %APPVEYOR_BUILD_FOLDER%
    # - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/horta/ci/master/appveyor.bat', 'appveyor.bat')" && appveyor.bat
    - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
    - pip install -U setuptools pip pypandoc
    - python setup.py build_ext --inplace
    - if errorlevel 1 exit 1
    - python setup.py test
    - if errorlevel 1 exit 1
    - pip install .
    - cd ..
    - python -c "import sys; import %PKG_NAME%; sys.exit(%PKG_NAME%.test())"
    - if errorlevel 1 exit 1
    - pip uninstall %PKG_NAME% --yes
    - cd %APPVEYOR_BUILD_FOLDER%
    - pip install -r requirements.txt
    - if exist doc\make.bat (
    -   cd doc && make.bat html
    -   if errorlevel 1 exit 1
    -   cd %APPVEYOR_BUILD_FOLDER%
    - )
    - python setup.py sdist
